Update OSG container actions to automatically generate the TIMESTAMP_TAG build variable [SOFTWARE-5317]
opensciencegrid/build-container-action pull request #8
Opened 2022-09-23 20:57 UTC by AidenCohen31

2022-09-26 22:39 UTC, brianhlin requested changes
Note that the timestamp is just the last bit of the `TIMESTAMP_TAG` (see the description for an example https://opensciencegrid.atlassian.net/browse/SOFTWARE-5317)

Also, in the future, make sure to squash/reword commits before submitting the PR! You may not want to rebase in this case since it appears that a merge commit snuck in

2022-09-27 18:57 UTC, AidenCohen31 commented
squashed commits

2022-10-04 19:30 UTC, AidenCohen31 commented
added more changes [SOFTWARE 5319]

2022-10-13 20:14 UTC, brianhlin commented
@AidenCohen31 it looks like there are some merge conflicts, could you sort those out?

2022-10-13 20:21 UTC, AidenCohen31 commented
Ok

On Thu, Oct 13, 2022, 3:15 PM Brian Lin ***@***.***> wrote:

> @AidenCohen31 <https://github.com/AidenCohen31> it looks like there are
> some merge conflicts, could you sort those out?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensciencegrid/build-container-action/pull/8#issuecomment-1278129389>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3ZOTPBPCVHLY52COT2FL3WDBUURANCNFSM6AAAAAAQUJXTCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-14 20:28 UTC, AidenCohen31 commented
needed to add the "" to the if statement as it would throw an error if name not specified

2022-12-07 22:41 UTC, brianhlin approved these changes
LGTM

2022-12-07 22:41 UTC, brianhlin commented on action.yml
> +        description: generated timestamp
```suggestion
        description: generated tag list
```

2022-12-07 22:41 UTC, brianhlin commented on action.yml
> +
```suggestion
```

Get rid of extra newline

2022-12-07 22:44 UTC, merged